name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Docker build
      run: | 
        cd src
        docker build -t cqrs-netcore-example:latest .
    - name: Docker tag 
      run: |
        docker tag cqrs-netcore-example:latest docker.pkg.github.com/nortal-blog/cqrs-netcore-example/cqrs-netcore-example:latest
    - name: Docker Publish
      run: |
        # docker push docker.pkg.github.com/nortal-blog/cqrs-netcore-example/cqrs-netcore-example:latest
